In [1]:
import cv2
import numpy as np

In [2]:
# 0 means black
img_1 = np.zeros((512, 512, 3))
print(img_1.shape)
# prints the shape of the image
cv2.imshow('Image', img_1)
cv2.waitKey(0)
cv2.destroyAllWindows()

(512, 512, 3)


In [3]:
print(img_1)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [14]:
img_2 = np.zeros((512, 512, 3))
# print(img_2)
cv2.imshow('Image', img_2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
img_2[:] = (255, 0, 0)
# the colon here indicates the entire image
cv2.imshow('Colored Image', img_2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
img_2[100:200, 300:500] = (0, 255, 0)
# here only this certain section remains colored
cv2.imshow('Cropped Colored Image', img_2)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Lines

In [7]:
cv2.line(img_2, (0, 0), (300, 300), (0, 0, 255), 3)
# arguments are
# the image on which we want the line, starting and ending coordinates, color, thickness
cv2.imshow('Line on Image', img_2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
# alternative method for entire image
# cv2.line(img_2, (0, 0), (img_2[1], img_2[0]), (0, 0, 255), 3)

#  Rectangles

In [9]:
cv2.rectangle(img_2, (0, 0), (250, 250), (0, 0, 255), 3)
# here coordinates means the diagonal coordinates
# cv2.rectangle(img_2, (0, 0), (250, 250), (0, 0, 255), cv2.FILLED)
# to get a filled rectangle
cv2.imshow('Rectangle on Image', img_2)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Circles

In [10]:
cv2.circle(img_2, (400, 50), 30, (255, 255, 0), 5)
# arguments are
# centre, radius, color, thickness
cv2.imshow('Circle on Image', img_2)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Text on Images

In [15]:
cv2.putText(img_2, 'OpenCV', (350, 150), cv2.FONT_ITALIC, 1, (150, 65, 78))
# arguments are
# image, text, starting point, font, scale, color
cv2.imshow('Text on Image', img_2)
cv2.waitKey(0)
cv2.destroyAllWindows()